spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${TENANT_ID}
        credential:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
        user-group:
          allowed-group-names: Admins,Developers
      keyvault:
        secret:
         property-sources[0]:
           endpoint: ${KEY_VAULT_URI}
        enabled: true
  data:
    mongodb:
      database: skillup-db
      uri: ${mongoConnectionUri}


server:
  forward-headers-strategy: native
  port: 8080
  servlet:
    context-path: /skillup